# Generated by Django 3.1.4 on 2020-12-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20201210_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.CharField(default='Escreva um breve resumo sobre o que vc vai falar!', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
